# Generated by Django 4.2.9 on 2024-01-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
