# Generated by Django 4.2.9 on 2024-01-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart_and_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[
                            ("PACZKOMAT", "Paczkomat"),
                            ("PACZKA_ORLEN", "Paczka Orlen"),
                            ("POCZTA_POLSKA", "Poczta Polska"),
                            ("KURIER", "Kurier"),
                        ],
                        default="Paczkomat",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_status",
                    models.CharField(default="Przygotowanie do wysyłki", max_length=20),
                ),
                ("shipping_street_number", models.CharField(max_length=10)),
                ("shipping_house_number", models.CharField(max_length=10)),
                ("shipping_street_name", models.CharField(max_length=255)),
                ("shipping_zip_code", models.CharField(max_length=10)),
                ("shipping_city", models.CharField(max_length=255)),
                ("shipping_email", models.EmailField(max_length=255)),
                ("shipping_first_name", models.CharField(max_length=255)),
                ("shipping_last_name", models.CharField(max_length=255)),
                ("shipping_phone_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("product_name", models.CharField(max_length=255)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart_and_orders.order",
                    ),
                ),
            ],
        ),
    ]
