# Generated by Django 4.2.9 on 2024-01-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_and_orders", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=21, max_digits=6),
        ),
    ]
